name: Test Workflow

on:
  push:
    branches:
      - '*'

jobs:
  code-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup GO
        uses: actions/setup-go@v5
        with:
          go-version: '^1.18'

      - name: Install dependencies
        working-directory: ./github-tracker
        run: go mod vendor

      - name: Check unit tests
        working-directory: ./github-tracker
        run: go test ./...
        continue-on-error: false
